# Generated by Django 3.0.4 on 2020-03-18 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_foodtype_typeimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='foods',
            name='typeid',
            field=models.IntegerField(default=1000),
        ),
    ]
