# Generated by Django 3.0.4 on 2020-03-18 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_foods_typeid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodtype',
            old_name='type2names',
            new_name='type2name',
        ),
    ]
