# Generated by Django 3.0.4 on 2020-03-19 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_auto_20200318_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foods',
            name='place',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='foods',
            name='type2id',
            field=models.IntegerField(blank=True, default=1000),
        ),
        migrations.AlterField(
            model_name='foods',
            name='type2name',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
