# Generated by Django 3.0.4 on 2020-03-19 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_auto_20200319_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foods',
            name='type2id',
            field=models.IntegerField(blank=True, default=1000, null=True),
        ),
        migrations.AlterField(
            model_name='foods',
            name='type2name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
