# Generated by Django 3.0.4 on 2020-03-21 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_auto_20200319_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='u_icon',
            field=models.ImageField(default='', upload_to='icons/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='u_phone',
            field=models.CharField(default='', max_length=64),
        ),
    ]
