# Generated by Django 3.0.4 on 2020-03-21 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_auto_20200321_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='u_password',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
