# Generated by Django 3.0.4 on 2020-03-26 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_auto_20200326_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='all_cost',
            field=models.IntegerField(default=0),
        ),
    ]
