# Generated by Django 3.0.4 on 2020-03-28 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_auto_20200328_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='c_foods_id',
        ),
        migrations.AddField(
            model_name='cart',
            name='c_foods',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='App.Foods'),
            preserve_default=False,
        ),
    ]
