# Generated by Django 3.0.4 on 2020-03-30 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_auto_20200328_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addr',
            name='a_tell',
            field=models.IntegerField(max_length=125),
        ),
    ]
