# Generated by Django 3.0.4 on 2020-03-30 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_auto_20200330_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addr',
            name='a_tell',
            field=models.IntegerField(),
        ),
    ]
