# Generated by Django 3.0.4 on 2020-04-01 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0015_auto_20200330_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addr',
            name='a_tell',
            field=models.CharField(max_length=64),
        ),
    ]
