# Generated by Django 3.0.4 on 2020-04-01 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0016_auto_20200401_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='o_id',
            field=models.BigIntegerField(default=202004010001),
        ),
        migrations.AlterField(
            model_name='order',
            name='o_note',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
