# Generated by Django 3.0.4 on 2020-04-02 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0017_auto_20200401_2211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderfoods',
            old_name='o_user',
            new_name='o_user_order',
        ),
    ]
