# Generated by Django 3.0.4 on 2020-04-05 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0019_order_o_use_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='points',
            name='is_order_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
