# Generated by Django 3.0.4 on 2020-04-05 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0021_insign'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insign',
            old_name='data',
            new_name='today',
        ),
    ]
